name: ROS CI

on: pull_request   # run on all pushes & PR's for every branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup directories
      run: mkdir -p catkin_ws/src
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: catkin_ws/src
    - name: setup ROS environment
      uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: melodic
    - name: install catkin_ws dependencies
      run: "cd catkin_ws && rosdep install"
    - name: build and test
      run: "source /opt/ros/melodic/setup.bash && catkin_make run_tests"
